# Welcome to Jekyll!
#

# Site settings
title: Roberto Preste
description: Bioinformatics, Data Science, Web Development
owner: Roberto Preste # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: roberto.preste@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robertopreste.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/robertopreste
  github: https://github.com/robertopreste
  linkedin-square: https://linkedin.com/in/robertopreste
  facebook-official: https://facebook.com/robertopreste
  google-plus-square: https://plus.google.com/u/0/+RobertoPreste
  email: mailto:roberto.preste@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Disqus comments
disqus:
  shortname: robertopreste
