# Welcome to Jekyll!
#

# Site settings
title: Roberto Preste
description: I build software and websites using powerful technologies.
owner: Roberto Preste # or company name
#first_published: 2018 # if migrating another site, the year of your first publish
email: roberto.preste@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robertopreste.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/robertopreste
  github: https://github.com/robertopreste
  medium: https://medium.com/@robertopreste
  linkedin-square: https://linkedin.com/in/robertopreste
  facebook-official: https://facebook.com/robertopreste
  email: mailto:roberto.preste@gmail.com
  #google-plus-square: https://plus.google.com/u/0/+RobertoPreste
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

logo: /images/favicon.png
image: /images/preste_roberto_web.jpg
image_large: /images/preste_roberto_large.jpg
google_site_verification_1: UA-111558547-1
google_site_verification_3: UA-111558547-3
google_site_verification_4: UA-111558547-4
google_site_verification_5: UA-111558547-5
lang: en_GB

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Disqus comments
disqus:
  shortname: robertopreste

# Code highlighting
highlighter: rouge

# Plugins

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
